"""Add delete flags to messages

Revision ID: 5bff479603ae
Revises: bd422cd0734f
Create Date: 2025-07-04 19:30:19.620900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bff479603ae'
down_revision: Union[str, Sequence[str], None] = 'bd422cd0734f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Yeni ve Doğru Hali
def upgrade() -> None:
    op.add_column('messages', sa.Column('deleted_by_sender', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('messages', sa.Column('deleted_by_receiver', sa.Boolean(), nullable=False, server_default='false'))

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'deleted_by_receiver')
    op.drop_column('messages', 'deleted_by_sender')
    # ### end Alembic commands ###
