"""Add password reset fields to user

Revision ID: 61124f473efc
Revises: 1eed5445bab0
Create Date: 2025-07-22 11:58:43.115621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61124f473efc'
down_revision: Union[str, Sequence[str], None] = '1eed5445bab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_showcase_posts_title'), table_name='showcase_posts')
    op.drop_table('showcase_posts')
    op.add_column('users', sa.Column('reset_password_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_password_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_reset_password_token'), 'users', ['reset_password_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_reset_password_token'), table_name='users')
    op.drop_column('users', 'reset_password_token_expires_at')
    op.drop_column('users', 'reset_password_token')
    op.create_table('showcase_posts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Gönderinin başlığı'),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Gönderi hakkında detaylı açıklama'),
    sa.Column('original_filename', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Kullanıcının yüklediği dosyanın orijinal adı'),
    sa.Column('file_format', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='Dosya uzantısı (örn: dwg, stp, rvt)'),
    sa.Column('storage_path', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Dosyanın sunucuda saklandığı göreceli yol (örn: static/uploads/uuid.stp)'),
    sa.Column('aps_urn', sa.VARCHAR(), autoincrement=False, nullable=True, comment='APS Viewer için modelin Base64 formatındaki kimliği (URN)'),
    sa.Column('aps_translation_status', sa.VARCHAR(), autoincrement=False, nullable=True, comment="APS'teki çeviri işleminin durumu: pending, inprogress, success, failed"),
    sa.Column('thumbnail_path', sa.VARCHAR(), autoincrement=False, nullable=True, comment='APS tarafından oluşturulan önizleme resminin yolu'),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False, comment="Bu gönderiyi oluşturan freelancer'ın ID'si"),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='Gönderinin oluşturulma zamanı'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Gönderinin son güncellenme zamanı'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('showcase_posts_owner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('showcase_posts_pkey')),
    sa.UniqueConstraint('aps_urn', name=op.f('showcase_posts_aps_urn_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('storage_path', name=op.f('showcase_posts_storage_path_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_showcase_posts_title'), 'showcase_posts', ['title'], unique=False)
    # ### end Alembic commands ###
