"""Add showcase_posts table and relationship to users

Revision ID: 6bd9aa9dc96d
Revises: 1eed5445bab0
Create Date: 2025-07-18 19:47:05.274986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bd9aa9dc96d'
down_revision: Union[str, Sequence[str], None] = '1eed5445bab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
