"""add_model_url_to_showcase_posts

Revision ID: 9e337be7b45a
Revises: 777096f90901
Create Date: 2025-07-23 15:22:28.016481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e337be7b45a'
down_revision: Union[str, Sequence[str], None] = '777096f90901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('showcase_posts', sa.Column('model_url', sa.String(), nullable=True))
    op.add_column('showcase_posts', sa.Column('model_format', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('showcase_posts', 'model_format')
    op.drop_column('showcase_posts', 'model_url')
    # ### end Alembic commands ###
