"""Increase character limit for encrypted fields

Revision ID: af673c3afe79
Revises: 0d417e45c58f
Create Date: 2025-08-03 02:43:14.776810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app import models

# revision identifiers, used by Alembic.
revision: str = 'af673c3afe79'
down_revision: Union[str, Sequence[str], None] = '0d417e45c58f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=models.user.EncryptedString(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=models.user.EncryptedString(length=128),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
