"""Add skill test questions and choices models

Revision ID: cd736a287149
Revises: 5e398f2e54ef
Create Date: 2025-07-07 15:44:12.430296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # YENİ IMPORT


# revision identifiers, used by Alembic.
revision: str = 'cd736a287149'
down_revision: Union[str, Sequence[str], None] = '5e398f2e54ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

test_status_enum = postgresql.ENUM('IN_PROGRESS', 'COMPLETED', name='teststatus')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ÖNCE ENUM TİPİNİ OLUŞTUR
    test_status_enum.create(op.get_bind())

    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.UUID(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['skill_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('test_results', sa.Column('status', test_status_enum, nullable=True)) # DÜZENLENDİ
    op.create_table('choices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('choice_text', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('choices')
    op.drop_column('test_results', 'status')
    op.drop_table('questions')

    # SONRA ENUM TİPİNİ SİL
    test_status_enum.drop(op.get_bind())