"""Add profile picture url to users

Revision ID: f3f3d2d842e7
Revises: 7a63f376a345
Create Date: 2025-07-03 10:05:07.726880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3f3d2d842e7'
down_revision: Union[str, Sequence[str], None] = '7a63f376a345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture_url', sa.String(), nullable=True))
    op.drop_column('users', 'profile_picture')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'profile_picture_url')
    # ### end Alembic commands ###
